[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate && npx tsc && npx prisma db push --schema=./prisma/schema.prisma && npx tsx src/utils/seed.ts"]

[start]
cmd = "node dist/index.js"
